torosweb/broker/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^upload$', views.upload, name='upload'),
    url(r'^uploadjson$', views.uploadjson, name='uploadjson'),
    url(r'^circular/(?P<alert_name>\w+)$', views.circular, name='circular'),
    url(r'^login$', views.user_login, name='login'),
    url(r'^logout$', views.user_logout, name='logout'),
    url(r'^alert/(?P<alert_name>\w+)$', views.alert_detail,
        name='alert_detail'),
]

torosweb/torosweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from wiki.urls import get_pattern as get_wiki_pattern
from django_nyt.urls import get_pattern as get_nyt_pattern

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include("winnow.urls", namespace='winnow')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^rb/', include('rbmanager.urls', namespace='rbmanager')),
    url(r'^broker/', include('broker.urls', namespace='broker')),
    url(r'^wiki/notifications/', get_nyt_pattern()),
    url(r'^wiki/', get_wiki_pattern())
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

torosweb/templates/wiki/base.html
{% extends "wiki/base_site.html" %}

{% block wiki_site_title %} - TOROS Wiki{% endblock %}

{% block wiki_header_branding %}
<a class="navbar-brand" href="/">The TOROS Project</a>
{% endblock %}

{% block wiki_header_navlinks %}
<ul class="nav navbar-nav">
  <li class="active"><a href="{% url 'winnow:index' %}">Winnow</a></li>
  <li class="active"><a href="{% url 'broker:index' %}">Broker</a></li>
  <li class="active"><a href="{% url 'wiki:root' %}">Wiki</a></li>
</ul>
{% endblock %}

{% block wiki_footer_logo %}
{% endblock %}

torosweb/templates/wiki/base_site.html
{% load sekizai_tags i18n wiki_tags static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block wiki_pagetitle %}{% endblock %}{% block wiki_site_title %} - django-\/\/  i K |{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="www.django-wiki.org">

    <!-- Le styles -->
    <link href="{% static "wiki/bootstrap/css/wiki-bootstrap.min.css" %}" rel="stylesheet">

    {% render_block "css" %}

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>

  <body>

    {% block wiki_body %}

    {% block wiki_navbar %}
    <div class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <!-- .navbar-toggle is used as the toggle for collapsed navbar content -->
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          {% block wiki_header_branding %}
          <a class="navbar-brand" href="{% url 'wiki:root' %}">django-\/\/ i K |</a>
          {% endblock %}
        </div>
        <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" id="wiki-search-form" method="GET" action="{% url 'wiki:search' %}">
            <div class="input-group">
              <input type="search" class="form-control search-query" name="q" placeholder="{% trans "Search..." %}" />
              <span class="input-group-btn">
                <button class="btn btn-default" type="submit">
                  <span class="fa fa-search"></span>
                </button>
              </span>
            </div><!-- /input-group -->
          </form>
          <div class="navbar-right">
            {% if user.is_authenticated %}
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <span class="badge notification-cnt">0</span>
                  {{ user }}
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  {% if "ACCOUNT_HANDLING"|wiki_settings %}
                  <li>
                    <a href="{% url 'wiki:profile_update' %}">
                      <i class="fa fa-gear"></i>
                      {% trans "Account Settings" %}
                    </a>
                  </li>
                  <li>
                    <a href="{% url 'wiki:logout' %}">
                      <i class="fa fa-power-off"></i>
                      {% trans "Log out" %}
                    </a>
                  </li>
                  {% endif %}
                  {% if user.is_superuser %}
                  <li>
                    <a href="{% url 'wiki:deleted_list' %}">
                      <i class="fa fa-trash-o"></i>
                      {% trans "Deleted articles" %}
                    </a>
                  </li>
                  {% endif %}
                  {% if "wiki.plugins.notifications"|plugin_enabled %}
                    {% include "wiki/plugins/notifications/menubaritem.html" %}
                  {% endif %}
                </ul>
              </li>
            </ul>
            {% else %}
            <ul class="nav navbar-nav">
              <li>
                <a href="{% login_url as wiki_login_url %}{{ wiki_login_url }}">{% trans "Log in" %}</a>
              </li>
              {% if "ACCOUNT_HANDLING"|wiki_settings %}
              <li>
                <a href="{% url 'wiki:signup' %}">{% trans "Sign up" %}</a>
              </li>
              {% endif %}
            </ul>
            {% endif %}
          </div>
          {% block wiki_header_navlinks %}
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">{% trans "Home" %}</a></li>
            <li><a href="https://github.com/django-wiki/django-wiki" target="_blank">{% trans "About" %}</a></li>
          </ul>
          {% endblock %}
        </div>
      </div>
    </div>
    {% endblock %}

    <div class="container" style="margin-top: 60px;">

      {% if messages %}
        <!-- Messages for this instance -->
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            <a class="close" data-dismiss="alert" href="#">&times;</a>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}

      <!-- Reserved for breadcrumbs -->
      {% block wiki_breadcrumbs %}{% endblock %}

      <!-- Main page contents go here -->
      {% block wiki_contents %}{% endblock %}

      <footer id="wiki-footer">
        <hr />
        {% block wiki_footer_logo %}
        <a href="https://github.com/django-wiki/django-wiki" class="pull-right"><img src="{% static "wiki/img/github_icon.png" %}" /></a>
        {% endblock %}
        {% block wiki_footer_prepend %}
        {% endblock %}
        <div style="clear: both"></div>
      </footer>
      </div>

    </div> <!-- /container -->

    {% endblock %}

    <script src="{% static "wiki/js/jquery.min.js" %}"></script>
    <script src="{% static "wiki/js/core.js" %}"></script>
    <script src="{% static "wiki/bootstrap/js/bootstrap.min.js" %}"></script>
    <!-- Optionally enable responsive features in IE8 -->
    <script src="{% static "wiki/js/respond.min.js" %}"></script>
    {% render_block "js" %}

  </body>
</html>