torosweb/broker/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^upload$', views.upload, name='upload'),
    url(r'^uploadjson$', views.uploadjson, name='uploadjson'),
    url(r'^circular/(?P<alert_name>\w+)$', views.circular, name='circular'),
    url(r'^login$', views.user_login, name='login'),
    url(r'^logout$', views.user_logout, name='logout'),
    url(r'^alert/(?P<alert_name>\w+)$', views.alert_detail,
        name='alert_detail'),
]

torosweb/torosweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from wiki.urls import get_pattern as get_wiki_pattern
from django_nyt.urls import get_pattern as get_nyt_pattern

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include("winnow.urls", namespace='winnow')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^rb/', include('rbmanager.urls', namespace='rbmanager')),
    url(r'^broker/', include('broker.urls', namespace='broker')),
    url(r'^wiki/notifications/', get_nyt_pattern()),
    url(r'^wiki/', get_wiki_pattern())
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

torosweb/winnow/urls.py
from django.conf.urls import url
from winnow import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^rank/$', views.rank, name='rank'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^object/(?P<object_slug>\w+)/$', views.object_detail, name='object_detail'),
    url(r'^profile/(?P<a_username>.+)/$', views.show_profile, name='profile_detail'),
    url(r'^data/$', views.data, name='data'),
]

torosweb/winnow/forms.py
from django import forms
from winnow.models import Ranking, UserProfile
from django.contrib.auth.models import User

class RankingForm(forms.ModelForm):
    RANKING_OPTIONS = ((1, 'Yes'),
                       (-1, 'No'),
                       (0, "I don't know"))
    rank = forms.ChoiceField(choices=RANKING_OPTIONS, widget=forms.RadioSelect, help_text="Options")
    isInteresting = forms.BooleanField(help_text = 'Mark as interesting', initial=False, required=False)
    #trans_candidate = forms.ForeignKey(widget=forms.HiddenInput())
    
    class Meta:
        model = Ranking
        fields = ('rank', 'isInteresting')

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    repeat_password = forms.CharField(widget=forms.PasswordInput())
    def clean_username(self):
        the_username = self.cleaned_data['username']
        print("Username chosen is: " + the_username)
        try:
            User.objects.get(username=the_username)
        except User.DoesNotExist:
            return the_username
        self._errors['username'] = ["Username already taken"]
        return the_username
    def clean(self):
        form_data = self.cleaned_data
        if form_data['password'] != form_data['repeat_password']:
            self._errors['password'] = ["Passwords do not match"] # Will raise a error message
            del form_data['password']
        return form_data
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password', 'repeat_password')

class UserProfileForm(forms.ModelForm):
    website = forms.URLField(label='Personal website', required=False)
    picture = forms.ImageField(label='Profile picture', required=False)
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

torosweb/winnow/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from winnow.forms import RankingForm, UserForm, UserProfileForm
from winnow.models import TransientCandidate, Ranking, UserProfile, Dataset
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout


# For the comments
from django_comments.models import Comment
from django.contrib.sites.shortcuts import get_current_site


def index(request):
    return render(request, 'winnow/index.html', {'page_index': 'selected'})


def rank(request):
    if not request.user.is_authenticated():
        context = {}
        context['message'] = {
            'headline': "Access denied",
            'body': "You need to be logged in to view this page"}
        return render(request, 'winnow/message.html', context)

    if request.method == "POST":
        form = RankingForm(request.POST)
        if form.is_valid():
            r = form.save(commit=False)
            r.ranker = UserProfile.objects.get(user=request.user)
            tc_id = int(request.POST.get('tc_id'))
            tc = TransientCandidate.objects.get(pk=tc_id)
            r.trans_candidate = tc
            r.save()

            # Now save the comment if there is one.
            comment_text = request.POST.get('comment')
            if len(comment_text) > 0:
                # save the comment
                new_comment = Comment()
                new_comment.user = request.user
                new_comment.user_name = request.user.username
                new_comment.user_email = request.user.email
                new_comment.user_url = UserProfile.objects.\
                    get(user=request.user).website
                new_comment.comment = comment_text
                new_comment.site = get_current_site(request)
                new_comment.content_object = tc
                new_comment.save()

            return redirect('winnow:rank')
        else:
            tc_id = int(request.POST.get('tc_id'))
            tc = TransientCandidate.objects.get(pk=tc_id)
    else:
        try:
            # Fetch any tc not ranked yet
            ds = Dataset.objects.filter(isCurrent=True).reverse()[0]
            tc = TransientCandidate.objects.filter(dataset=ds).\
                exclude(ranking__in=Ranking.objects.all())[0]
        except IndexError:
            # Fetch any tc not ranked by the current user
            try:
                current_user = UserProfile.objects.get(user=request.user)
                ds = Dataset.objects.filter(isCurrent=True).reverse()[0]
                tc = TransientCandidate.objects.filter(dataset=ds)\
                    .exclude(
                        ranking__in=Ranking.objects.filter(ranker=current_user))[0]
            except IndexError:
                tc = None

        if tc is None:
            tc_id = -1
        else:
            tc_id = tc.id

        form = RankingForm()

    return render(request, 'winnow/rank.html',
                  {'form': form, 'page_rank': 'selected',
                   'tc_id': tc_id, 'object': tc})


def about(request):
    return render(request, 'winnow/about.html', {'page_about': 'selected'})


def object_detail(request, object_slug):
    trans_obj = TransientCandidate.objects.get(slug=object_slug)
    ranked_interesting = Ranking.objects\
        .filter(trans_candidate=trans_obj)\
        .filter(isInteresting=True)
    int_users_list = UserProfile.objects.filter(ranking=ranked_interesting)
    int_counts = len(int_users_list)

    if request.method == "POST":
        if request.user.is_authenticated():
            # Save the comment if there is one.
            comment_text = request.POST.get('comment')
            if len(comment_text) > 0:
                # save the comment
                new_comment = Comment()
                new_comment.user = request.user
                new_comment.user_name = request.user.username
                new_comment.user_email = request.user.email
                new_comment.user_url = \
                    UserProfile.objects.get(user=request.user).website
                new_comment.comment = comment_text
                new_comment.site = get_current_site(request)
                new_comment.content_object = trans_obj
                new_comment.save()

    return render(request, 'winnow/trans_detail.html',
                  {'object': trans_obj, 'interesting_count': str(int_counts),
                   'interesting_user_list': int_users_list})


def register(request):
    registered = False

    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves,
            # we set commit=False.
            # This delays saving the model until we're ready
            # to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form
            # and put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to tell the template registration was
            # successful.
            registered = True

            # Now the user has been created, log them in
            newusername = request.POST.get('username')
            newpassword = request.POST.get('password')
            newuser = authenticate(username=newusername, password=newpassword)
            if newuser:
                if newuser.is_active:
                    login(request, newuser)
                    return redirect('winnow:index')
                else:
                    context = {}
                    context['message'] = {
                        'headline': "Error loggin in",
                        'body': "Sorry, your account has been disabled."}
                    return render(request, 'winnow/message.html', context)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'winnow/register.html',
                  {'user_form': user_form, 'profile_form': profile_form,
                   'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)

                # This returns users to whatever page they were when logged in
                if request.POST['next']:
                    return redirect(request.POST['next'])
                else:
                    return redirect('winnow:index')
            else:
                return HttpResponse("Your account is disabled.")
        else:
            return HttpResponse("Invalid login details supplied.")

    else:
        return render(request, 'winnow/login.html', {})


def user_logout(request):
    if request.user.is_authenticated():
        logout(request)
    return redirect('winnow:index')


def show_profile(request, a_username):
    try:
        the_user = User.objects.get(username=a_username)
        the_userprofile = UserProfile.objects.get(user=the_user)
    except:
        the_userprofile = None
    return render(request, 'winnow/profile_detail.html',
                  {'the_userprofile': the_userprofile})


def data(request):
    if not request.user.is_superuser:
        context = {}
        context['message'] = {
            'headline': "Access denied",
            'body': "You need to be a logged in superuser to view this page"}
        return render(request, 'winnow/message.html', context)

    from django.db.models import Sum
    if request.method == 'POST':
        dataset = request.POST['dataset']
        alltc = TransientCandidate.objects.filter(dataset__name=dataset)

        from django.conf import settings
        import os
        from django.utils import timezone
        dumpfilename = os.path.join(settings.MEDIA_ROOT,
                                    'db_dumps/%s_dump.txt' % (dataset))
        dumpfile = open(dumpfilename, 'w')
        dumpfile.write("#" + str(timezone.now()) + "\n")
        dumpfile.write(
            "#unique_id, object id, dataset id, file name, x_pix, y_pix, "
            "RA, Dec, height, width, original magnitude, "
            "reference magnitude, subtraction magnitude, ranking\n")

        for atc in alltc:
            aline = "%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, " % \
                (atc.slug, atc.object_id, dataset, atc.filename, atc.x_pix,
                 atc.y_pix, atc.ra, atc.dec, atc.height, atc.width,
                 atc.mag_orig, atc.mag_ref, atc.mag_subt)

            rbclass = atc.ranking_set.all().\
                aggregate(Sum('rank'))['rank__sum']
            rbclass = rbclass if rbclass is not None else 0
            aline += "%d\n" % (rbclass)
            dumpfile.write(aline)
        dumpfile.close()

        from django.core.servers.basehttp import FileWrapper
        wrapper = FileWrapper(file(dumpfilename))

torosweb/templates/winnow/data_interface.html
{% extends 'base.html' %}

{% load winnow_tags %}

{% block title %}Winnow - Home{% endblock %}

{% block content %}

<section id="content">

<div id="block" style="width:90%; margin:1em auto; border:2px; display:inline-block">
    <h1>Data Set Information</h1>
    <br>
    <form id="dump_db" method="post" action="{% url 'data' %}">
        {% csrf_token %}
        <fieldset>
            <legend>Request a DB Dump</legend>
            <p>
            <label>Select Data Set</label>
            <select name="dataset">
            {% for ads in datasets %}
               <option value = "{{ads.name}}">{{ads.name}}</option>
            {% endfor %}
            </select>
          </p>
       </fieldset>
        Click here to get all your data: <input type="submit" class="button" name="submit" value="Request DB Dump" />
    </form>
</div>

<div id="block" style="width:90%; margin:1em auto; border:2px; display:inline-block">
    <h3>Statistics</h3>
    <table cellspacing="0">
        <tr>
            <th>Dataset Name</th>
            <th>Reals</th>
            <th>Bogus</th>
            <th>Unclassified</th>
            <th>Not Ranked</th>
            <th>Total</th>
        </tr>
        {% for ads in datasets %}
        <tr>
            <td>{{ ads.name }}</td>
            <td>{{ ads.number_of_reals }}</td>
            <td>{{ ads.number_of_bogus }}</td>
            <td>{{ ads.number_of_unclassified }}</td>
            <td>{{ ads.number_not_ranked }}</td>
            <td>{{ ads.number_of_objects }}</td>
        </tr>
        {% endfor %}
    </table>
</div>

</section>
{% endblock %}

torosweb/templates/winnow/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Winnow - Home{% endblock %}

{% block content %}

		<section id="content">

		<h2>Welcome to the training workshop for TOROS </h2>
		<p>The Transient Optical Robotic Observatory of the South (TOROS) needs your amazing pattern-recognition ability to differentiate between unreal and real image detection.</p>
		<p>Image differencing leaves behind many unreal (bogus) objects due to bad subtraction. Such images will be classified as bogus by a Machine Learning (ML) algorithm. This ML algorithm has to be “trained” with labeled data. This is where you come in. Your classification of, real or bogus images, will generate this training data set.</p>
		<p>As a volunteer on this website, you can become a citizen scientist and citizen researcher, participating in real science and other research. If you think you have made a mistake, do not worry. This project is set up to have more than one volunteer analyzing each piece of data, thereby eliminating the vast majority of human error. Mistakes are a part of the process, and can even help us evaluate the difficulty of the data. As long as everyone does their best, they are helping!</p>
		<p>A short training tutorial is available. Please register and create an account to contribute and collaborate with TOROS.</p>

		<a href="{% url 'register' %}" class="button">Register</a>
		<a href="{% url 'login' %}" class="button">Log In</a>
		<a href="{% url 'rank' %}" class="button">Start Tutorial</a>
		
	</section>
{% endblock %}

torosweb/templates/winnow/login.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Winnow - Login{% endblock %}

{% block content %}
<section id="content">
    <h1>Login</h1>

     <fieldset>
     	<legend>Log in</legend>
    	<form id="login_form" method="post" action="{% url 'login' %}">
		{% csrf_token %}					
		
        <p><label for="name">Username:</label>
        <input name="username" id="name" value="" type="text" /></p>
		
        <p><label for="password">Password:</label>
        <input name="password" id="password" value="" type="password" /></p>
        <input type="hidden" name="next" value="{% url 'index' %}" />


        <p><input name="submit" style="margin-left: 150px;" class="formbutton" value="Log in" type="submit" /></p>
        </form>
    </fieldset>

</section>
{% endblock %}

torosweb/templates/winnow/profile_detail.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load winnow_tags %}

{% block title %}Winnow - Profile Page{% endblock %}

{% block content %}
<section id="content">
	{% if the_userprofile %}
		<div id="profilepic_big" style="float:left; padding:1em; margin-top:1em;">
			{% if the_userprofile.picture %}
				<img src="{{ the_userprofile.picture.normal.url }}" align=left />
			{% else %}
				<img src="/media/profile_images/default.normal.png" align=left />
			{% endif %}
		</div><!-- profilepic_big -->
		<div id="profileInfo" style="float:left; padding:1em; margin-top:1em;">
			<h5 style="display:inline;">Username:</h5> {{ the_userprofile.user.username }} <br>
			{% if the_userprofile.fullname %}<h5 style="display:inline;">Full Name:</h5> {{ the_userprofile.fullname }} <br>{% endif %}
			{% if the_userprofile.affiliation %}<h5 style="display:inline;">Affiliation:</h5> {{ the_userprofile.affiliation }} <br>{% endif %}
			{% if the_userprofile.website %}<h5 style="display:inline;">Personal Website:</h5> <a href="{{ the_userprofile.website }}"> {{ the_userprofile.website }} </a><br>{% endif %}
			{% if the_userprofile.user.username == user.username %}
				<a href="#">Edit profile</a><br>
			{% endif %}
		</div><!-- profileinfo -->
		<div style="clear:both;"></div>
		<p>{{ the_userprofile.user.username }} has ranked {{ the_userprofile.number_of_votes }} transients.</p>
		<h3>My Interesting objects:</h3><br>
		<div style="max-height: 30em; overflow: auto; padding-right: 2em;">
		<ul>
		{% for obj in the_userprofile.interesting_objects %}
		 <li><a href="{% url 'object_detail' obj.slug %}">{{ obj }}</a></li>
		{% endfor %}
	    </ul>
		</div>

		<h3>My comments:</h3>
		<div style="max-height: 30em; overflow: auto; padding-right: 2em;">
		{% for comment in the_userprofile.comments %}
		<i>On {{ comment.submit_date }}, {{ comment.user }} wrote about object
			<a href="{% url 'object_detail' comment.content_object.slug %}">
				{{comment.content_object.slug}}
			</a>:
		</i>
		<blockquote><p>{{ comment.comment }}</p></blockquote>
		<hr width="90%" align="left">
		{% endfor %}
		</div>
			
	{% else %}
		<br>
		<h3>Sorry, no profile found.</h3>
	{% endif %}
</section>
{% endblock %}

torosweb/templates/winnow/rank.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load comments %}
{% load winnow_tags %}

{% block title %}Winnow - Training Page{% endblock %}

{% block content %}
	<section id="content">
	{% if user.is_authenticated %}
	{% if object %}
	<h1 style="margin-top:1em;">Is this a real transient?</h1>
	<div id="all_plots" style="width:90%; margin:1em auto; background-color:#eee; border:2px outset #aaa; display:inline-block; border-radius:10px">
		<div id="orig" class="plot">
			<img src="{{ object.origImg.normal.url }}" width=100%/>
			<h5 style="text-align:center;">Candidate</h5>
		</div><!--orig-->
		<div id="ref" class="plot">
			<img src="{{ object.refImg.normal.url }}" width=100%/>
			<h5 style="text-align:center;">Reference</h5>
		</div><!--ref-->
		<div id="subtraction" class="plot">
			<img src="{{ object.subtImg.normal.url }}" width=100%/>
			<h5 style="text-align:center;">Subtraction</h5>
		</div><!--subtraction-->
	</div><!-- all_plots -->

	<div style="clear:both;"></div>

    <h5>Meta data</h5>
    {% include "winnow/trans_cand_infobox.html" %}

	<form id="page_form" method="post" action="{% url 'rank' %}">
	<div id="form_widgets" style="padding:1em;">
		<style type="text/css">
			#id_rank {
				list-style-type: none;
				display:inline;
			}
			#id_rank li {
				display:inline;
				margin:0px 1em;
			}
		</style>

		<input type="hidden" value="{{ object.pk }}" name="tc_id">

		{% csrf_token %}
		{% for hidden in form.hidden_fields %}
			{{ hidden }}
		{% endfor %}

		{% for field in form.visible_fields %}
			<div style="border-bottom:1px #ddd solid; padding:1em;">
			{{ field.errors }}
			{% if field.name == "isInteresting" %}
				<h5 style="display:inline;">{{ field.help_text }}:</h5>
			{% else %}
				<h5>{{ field.help_text }}:</h5>
			{% endif %}
			{{ field }}
			</div>
		{% endfor %}

	</div><!-- form_widgets -->

	<div id="add_comment" style="padding:1em;">
		You can add a comment below<br>
		{% get_userprofile user as userprofile %}
		{% if userprofile.picture %}
			<div class="profilethumb" style="background-image:url({{ userprofile.picture.thumbnail.url }}); float:left; margin:0.3em"></div>
		{% else %}
			<div class="profilethumb" style="background-image:url(/media/profile_images/default.normal.png); float:left; margin:0.3em"></div>
		{% endif %}
		<textarea name="comment" rows="5" cols="50" wrap="soft" maxlength="3000" style="float:left; display:inline-block; height:50px; margin:0.3em;"></textarea>
	</div><!-- add_comment -->
	<div style="clear:both;"></div>
	<br>
	<input type="submit" class="formbutton" name="submit" value="Rank Transient" />
	
	</form>

	{% else %}
		<p>Congratulations! You classified all transients available at the moment.</p>
	{% endif %}
				
	{% else %}
		<p>You need to be logged in to classify objects.</p>
	{% endif %}
	</section>
{% endblock %}

torosweb/templates/winnow/register.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Winnow - Register{% endblock %}

{% block content %}
<section id="content">
    <h1>Register to Winnow</h1>

    {% if registered %}
    	<p><strong>Thank you for registering!</strong></p>
    	<p><a href="{% url 'index' %}">Return to the homepage.</a></p><br />
    {% else %}
     <fieldset>
     	<legend>Required fields are marked in red</legend>
    	<form id="user_form" method="post" action="{% url 'register' %}" enctype="multipart/form-data">
		{% csrf_token %}
		{% for field in user_form %}
    		<p>{% if field.field.required %}
				<span class="required">
				<label for="{{ field.name }}">{{ field.label }}:</label>
			    </span>
			{% else %}
		        <label for="{{ field.name }}">{{ field.label }}:</label>
			{% endif %}
			{{ field }}
		    {% for error in field.errors %}
		 	    <i>({{ error }})</i>
		    {% endfor %}
		</p>
		{% endfor %}
		{% for field in profile_form %}
		    <p>{% if field.field.required %}
			    <span class="required">
        	    <label for="{{ field.name }}">{{ field.label }}:</label>
				</span>
			    {% else %}
        	    <label for="{{ field.name }}">{{ field.label }}:</label>
				{% endif %}
			{{ field }}
		    {% for error in field.errors %}
		 	    <i>({{ error }})</i>
		    {% endfor %}
		</p>
		{% endfor %}					
        <p><input name="submit" style="margin-left: 150px;" class="formbutton" value="Register" type="submit" /></p>
        </form>
    </fieldset>
    {% endif %}
</section>

{% endblock %}

torosweb/templates/winnow/trans_detail.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load comments %}
{% load winnow_tags %}

{% block title %}Winnow - Detail View {{ object.slug }}{% endblock %}
{% block header_extra %}
<script src="{% static "js/d3.v3.min.js" %}"></script>
<link rel="stylesheet" type="text/css" href="{% static "css/barplot.css" %}">
<script>
var real_votes = {{ object.number_of_real_votes }}
var bogus_votes = {{ object.number_of_bogus_votes }}
var unknown_votes = {{ object.number_of_unclassified_votes }}
</script>
{% endblock %}

{% block content %}
	<section id="content">

    <div id="all_plots" style="width:90%; margin:1em auto; background-color:#eee; border:2px outset #aaa; display:inline-block; border-radius:10px;">
    	<div id="orig" class="plot">
    		<img src="{{ object.origImg.normal.url }}" width=100%/>
    		<h5 style="text-align:center;">Candidate</h5>
    	</div><!--orig-->
    	<div id="ref" class="plot">
    		<img src="{{ object.refImg.normal.url }}" width=100%/>
    		<h5 style="text-align:center;">Reference</h5>
    	</div><!--ref-->
    	<div id="subtraction" class="plot">
    		<img src="{{ object.subtImg.normal.url }}" width=100%/>
    		<h5 style="text-align:center;">Subtraction</h5>
    	</div><!--subtraction-->
    </div><!-- all_plots -->

    <h5>Meta data</h5>
    {% include "winnow/trans_cand_infobox.html" %}

	<h5>Ranking</h5>
	<div id=barplot>
	</div>
	<script src="{% static 'js/barplot.js' %}"></script>
	
	<h5>Likes</h5>
		{% if interesting_count != 0 %}
		It has been marked interesting {{ interesting_count }} time{%if interesting_count != "1" %}s{% endif %} by:<br>
		<ul style="list-style: none; padding: 0; margin: 0;">
		{% for name in interesting_user_list %}
			<li><a href="{% url 'profile_detail' name %}">{{ name }}</a></li>
		{% endfor %}
	    </ul>
		<br>
		{% endif %}
			
		{% get_comment_count for winnow.transientcandidate object.pk as comment_count %}
		<h5>This object has {{ comment_count }} comment{%if comment_count != "1" %}s{% endif %}</h5>
		{% render_comment_list for winnow.transientcandidate object.pk %}
		<br>
		
		{% if user.is_authenticated %}
		<form id="page_form" method="post" action="{% url 'object_detail' object.slug %}">
		{% csrf_token %}
		<input type="hidden" value="{{ object.pk }}" name="tc_id">
		<p>Enter your comment below</p>
		<textarea name="comment" rows="5" cols="50" wrap="soft" maxlength="3000"></textarea>
		<br>
		<input type="submit" name="submit" value="Comment" />
		</form>
		{% endif %}
		
	</section>
{% endblock %}