torosweb/broker/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^upload$', views.upload, name='upload'),
    url(r'^uploadjson$', views.uploadjson, name='uploadjson'),
    url(r'^circular/(?P<alert_name>\w+)$', views.circular, name='circular'),
    url(r'^login$', views.user_login, name='login'),
    url(r'^logout$', views.user_logout, name='logout'),
    url(r'^alert/(?P<alert_name>\w+)$', views.alert_detail,
        name='alert_detail'),
]

torosweb/rbmanager/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

torosweb/torosweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from wiki.urls import get_pattern as get_wiki_pattern
from django_nyt.urls import get_pattern as get_nyt_pattern

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include("winnow.urls", namespace='winnow')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^rb/', include('rbmanager.urls', namespace='rbmanager')),
    url(r'^broker/', include('broker.urls', namespace='broker')),
    url(r'^wiki/notifications/', get_nyt_pattern()),
    url(r'^wiki/', get_wiki_pattern())
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

torosweb/winnow/urls.py
from django.conf.urls import url
from winnow import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^rank/$', views.rank, name='rank'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^object/(?P<object_slug>\w+)/$', views.object_detail, name='object_detail'),
    url(r'^profile/(?P<a_username>.+)/$', views.show_profile, name='profile_detail'),
    url(r'^data/$', views.data, name='data'),
]

torosweb/rbmanager/models.py
from django.db import models

from winnow.models import UserProfile, Dataset


class Experiment(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    dataset = models.ForeignKey(Dataset)
    date = models.DateField('date of experiment')
    SOFTWARE = (
        ('0', 'Weka'),
        ('1', 'RapidMiner'),
        ('2', 'scikit-learn'),
        ('3', 'Other'),
    )
    platform = models.CharField(
        'software used', max_length=1, choices=SOFTWARE, default='0')
    other_platform_name = models.CharField(max_length=20,
                                           null=True, blank=True)
    alg_name = models.CharField('algorithm name', max_length=50)
    params_file = models.FileField('parameter file name',
                                   max_length=50, null=True, blank=True)
    labels_file = models.FileField('label file name', null=True, blank=True)

    features = models.ManyToManyField('Feature')
    featureset_infofile = models.FileField('feature set file name',
                                           null=True, blank=True)
    featuretable_datafile = models.FileField('feature table file name',
                                             null=True, blank=True)

    conf_mat_rr = models.IntegerField('reals classified as reals')
    conf_mat_rb = models.IntegerField('reals classified as bogus')
    conf_mat_br = models.IntegerField('bogus classified as reals')
    conf_mat_bb = models.IntegerField('bogus classified as bogus')
    confusion_table_file = models.FileField(
        'confusion matrix file name', null=True, blank=True)

    other_outputfiles = models.TextField(
        'other output files', null=True, blank=True)
    other_inputfiles = models.TextField(
        'other input files', null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    is_favorite = models.BooleanField(default=False)

    def recall(self):
        "Return the Recall: Proportion of Real Positive cases "\
            "that are correctly Predicted Positive."
        r = float(self.conf_mat_rr) / float(self.conf_mat_rr +
                                            self.conf_mat_rb)
        return r

    def precision(self):
        "Return the Precision: Proportion of Predicted Positive cases"\
            "that are correctly Real Positives"
        p = float(self.conf_mat_rr) / float(self.conf_mat_rr +
                                            self.conf_mat_br)
        return p

    def f_measure(self):
        r = float(self.conf_mat_rr) / float(self.conf_mat_rr +
                                            self.conf_mat_rb)
        p = float(self.conf_mat_rr) / float(self.conf_mat_rr +
                                            self.conf_mat_br)
        return 2. * p * r / (p + r)

    def false_positive_rate(self):
        return (float(self.conf_mat_br) /
                float(self.conf_mat_rr + self.conf_mat_br))

    def miss_rate(self):
        return (float(self.conf_mat_rb) /
                float(self.conf_mat_rb + self.conf_mat_bb))

    def predicted_reals(self):
        return self.conf_mat_rr + self.conf_mat_br

    def predicted_bogus(self):
        return self.conf_mat_rb + self.conf_mat_bb

    def total_reals(self):
        return self.conf_mat_rr + self.conf_mat_rb

    def total_bogus(self):
        return self.conf_mat_br + self.conf_mat_bb

    def total_samples(self):
        return (self.conf_mat_rr + self.conf_mat_rb + self.conf_mat_br +
                self.conf_mat_bb)

    def __str__(self):
        if self.platform != '3':
            p_name = self.get_platform_display()
        else:
            if self.other_platform_name is None:
                p_name = "Other"
            else:
                p_name = self.other_platform_name
        return "#{}: {} in {}".format(self.id, self.alg_name, p_name)

    class Meta:
        ordering = ('-date',)


class Feature(models.Model):
    name = models.CharField(max_length=20, unique=True)
    code = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

torosweb/rbmanager/forms.py
from .models import Experiment
from django import forms


class ExperimentForm(forms.ModelForm):
    features = forms.CharField(
        widget=forms.Textarea(attrs={
            'placeholder': "feature1: some description, feature2, "
            "feature3, feature4: another description"}),
        required=False)

    class Meta:
        model = Experiment
        exclude = ['user']
        widgets = {
            'date': forms.DateInput(attrs={'class': 'datepicker'}),
        }

    def clean(self):
        cleaned_data = super(ExperimentForm, self).clean()
        alg_name = self.cleaned_data.get('alg_name', None)
        if alg_name is not None:
            cleaned_data['alg_name'] = alg_name.title()

        def feature_set(feature_text_field):
            def parse_descriptions(astr):
                the_split = astr.split(':')
                if len(the_split) == 1:
                    return [astr.strip(), ""]
                else:
                    return [the_split[0].strip(), the_split[1].strip()]

            return [parse_descriptions(afeat)
                    for afeat in feature_text_field.split(',')]

        the_feat = self.cleaned_data.get('features', None)
        if the_feat is not None:
            cleaned_data['features'] = feature_set(the_feat)

        return cleaned_data

torosweb/rbmanager/views.py
from django.shortcuts import render
from django.core.exceptions import ObjectDoesNotExist

from .models import Experiment, Feature
from .forms import ExperimentForm

from winnow.models import UserProfile


def index(request):
    if request.method == "POST":
        notification_failed = {'value': True, 'type': 'danger',
                               'message': 'The experiment could not be saved'}
        notification_passed = {'value': True, 'type': 'success',
                               'message': 'The experiment has been saved.'}
        exp_form = ExperimentForm(request.POST)
        if exp_form.is_valid():
            # Process form
            if request.user.is_authenticated():
                new_exp = exp_form.instance
                try:
                    user_prof = request.user.userprofile
                except ObjectDoesNotExist:
                    user_prof = UserProfile(user=request.user)
                    user_prof.save()
                    notification_passed['message'] += \
                        " A new profile has been created for the user."
                new_exp.user = user_prof
                new_exp.save()

                # Create and save the associated features
                all_features = []
                for name, description in exp_form.cleaned_data['features']:
                    new_feat, created = Feature.objects.\
                        get_or_create(name=name.lower())
                    if description != '' and (new_feat.description is None
                                              or new_feat.description == ''):
                        new_feat.description = description

                    new_feat.save()
                    all_features.append(new_feat)
                new_exp.features.add(*all_features)

                notification = notification_passed
                exp_form = ExperimentForm()
            else:  # if user is not authenticated
                notification_failed['message'] = "You need to be logged in " \
                    "to upload an experiment."
                notification = notification_failed

        else:  # if form is not valid:
            notification = notification_failed

    else:  # if request.method == "GET" or otherwise
        exp_form = ExperimentForm()
        notification = {'value': False, 'type': '', 'message': ''}

    return render(request, 'rbmanager/index.html',
                  {'exp_form': exp_form,
                   'experiment_list': Experiment.objects.all(),
                   'notification': notification})


def dataset_detail(request):
    return render(request, 'rbmanager/dataset_detail.html')

torosweb/rbmanager/templates/rbmanager/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}ML Experiment Manager{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    {% block header_extra %}
    {% endblock %}
</head>

<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">RealBogus</a>
        </div class="navbar-header">
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#">Graphs</a></li>
            <li><a href="#">Compare</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
                {% if user.is_active %}
                <div class="btn-group">
                  <a href="{% url 'winnow:profile_detail' user.username %}" type="button" class="btn btn-primary btn-sm">
                    {{ user.username }}
                  </a>
                  <a href="{% url 'winnow:logout' %}" type="button" class="btn btn-danger btn-sm">Log out</a>
                </div>
                {% else %}
                <div class="btn-group">
                  <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#loginmodal">Login</button>
                  <a href="{% url 'winnow:register' %}" type="button" class="btn btn-success btn-sm">Sign Up!</a>
                </div>
                {% include "rbmanager/login_form.html" %}
                {% endif %}
            </li>
          </ul class="nav navbar-nav navbar-right">
        </div class="collapse navbar-collapse" id="myNavbar">
    </div class="container-fluid">
</nav class="navbar navbar-inverse">
    {% block bodycontent %}
    {% endblock %}
</body>
</html>

torosweb/rbmanager/templates/rbmanager/dataset_modal.html
<!-- Modal -->
<div id="datasetmodal" class="modal" role="dialog">
  <div class="modal-dialog modal-sm">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">{{ dataset_object.name }}</h4>
      </div>

      <div class="modal-body">

        <div class="well">
        <dl>
          <dt>Start Date:</dt> <dd>{{ dataset_object.start_datetime|default_if_none:"Not specified" }}</dd>
          <dt>End Date:</dt> <dd>{{ dataset_object.end_datetime|default_if_none:"Not specified" }}</dd>
          <dt>Cadence:</dt> <dd>{{ dataset_object.cadence_sec|default_if_none:"Not specified" }} s</dd>
          <dt>Number of files:</dt> <dd>{{ dataset_object.number_of_files|default_if_none:"Not specified" }}</dd>
          {% if dataset_object.subset_of %}
          <dt>Subset of:</dt> <dd>{{ dataset_object.subset_of.name }}</dd>
          {% endif %}
          <dt>Description:</dt> <dd>{{ dataset_object.description|default_if_none:"No description" }}</dd>
      </dl>
      </div class="well">
      </div class="modal-body">
      <div class="modal-footer">
        {% if dataset_object.isCurrent %}
        <p>{{ dataset_object.name }} is the active dataset being labeled.</p>
        {% endif %}
      </div class="modal-footer">

    </div class="modal-content">

  </div class="modal-dialog">
</div id="datasetmodal" class="modal fade" role="dialog">

torosweb/rbmanager/templates/rbmanager/index.html
{% extends 'rbmanager/base.html' %}

{% block header_extra %}
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
{% endblock %}

{% block bodycontent %}

<div class="container-fluid">
    <div class="page-header">
        <h1>Real-Bogus Classifier</h1>
    </div class="page-header">


    <ul class="nav nav-tabs">
      <li class="active"><a href="{% url 'rbmanager:index' %}">Data</a></li>
      <li><a href="#">Upload</a></li>
  </ul>

  <h1>Browse past experiments or input a new one</h1>

    {% if notification.value %}
    <div class="alert alert-{{ notification.type }}">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        {{ notification.message }}
    </div>
    {% endif %}

  <div class="panel panel-primary">
      <div class="panel-heading">
        <h6 class="panel-title">        
        <a data-toggle="collapse" href="#enterexp">
        <span class="caret"></span>
        Enter your new experiment here 
        </a>
        </h6>

      </div>
      <div class="panel-collapse collapse" id="enterexp">
      <div class="panel-body">

            <form role="form" method="post" action="{% url 'rbmanager:index' %}">
            {% csrf_token %}
            {% for field in exp_form %}
            <div class="form-group">
            {% if field.field.required %}
                <span class="required">
                {{ field.label_tag }}
                </span>
            {% else %}
                {{ field.label_tag }}
            {% endif %}
            {{ field }}
            {% for error in field.errors %}
                <i>({{ error }})</i>
            {% endfor %}
            </div class="form-group">
            {% endfor %}
            <input name="submit" class="btn btn-default" value="Submit" type="submit" />
            </form>

        </div class="panel-body">
      </div>
  </div class="panel panel-primary">


<div class="panel panel-primary">
  <div class="panel-heading">Latest Experiments</div>
  <div class="panel-body">
    {% if experiment_list %}
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead>
              <tr>
                <th class="col-sm-1">ID</th>
                <th class="col-md-1">Date</th>
                <th class="col-md-1">User</th>
                <th class="col-md-1">Dataset</th>
                <th class="col-md-1">Algorithm</th>
                <th class="col-md-1">Features</th>
                <th class="col-md-1">Confusion Matrix
                  <table style="border: 1px solid;">
                    <thead>
                    <tr>
                        <th style="padding: 2px; border-right: 1px solid; background-color: #9cf799; border-bottom: 1px solid;">true reals</td>
                        <th style="padding: 2px; background-color: #f79292; border-bottom: 1px solid;">false reals</td>
                        <th style="padding: 2px; border: 1px solid;">tr + fr</td>
                    </tr>
                    <tr>
                        <th style="padding: 2px; border-right: 1px solid; background-color: #f79292; ">false bogus</td>
                        <th style="padding: 2px; background-color: #9cf799;">true bogus</td>
                        <th style="padding: 2px; border: 1px solid;">fb + tb</td>
                    </tr>
                    <tr>
                        <th style="padding: 2px; border: 1px solid;">tr + fb</td>
                        <th style="padding: 2px; border: 1px solid;">fr + tb</td>
                        <th style="padding: 2px; border: 1px solid;">N</td>
                    </tr>
                </table>
                </th>
                <th class="col-md-1">Measures</th>
                <th class="col-md-1">Platform</th>
                <th class="col-md-1">Description</th>
              </tr>
            </thead>
        <tbody>
            {% for exp in experiment_list %}
          <tr>
            <td>{{ exp.pk }}</td>
            <td>{{ exp.date }}</td>
            <td><a href="{% url 'winnow:profile_detail' exp.user %}">{{ exp.user }}</a></td>
            <td>
              <a data-toggle="modal" data-target="#datasetmodal">
                {{ exp.dataset }}
              </a>
                {% include "rbmanager/dataset_modal.html" with dataset_object=exp.dataset %}
            </td>
            <td>{{ exp.alg_name }} </td>
            <td>
              {% for feat in exp.features.all %}
              <a href="#" data-toggle="tooltip" title="{{ feat.description|default_if_none:'No description' }}">
              {% if forloop.last %}{{ feat.name }}{% else %}{{ feat.name }},{% endif %}
              </a>
              {% endfor %}
            </td>
            <td>
                <div class="well" style="width: 100%;">
                <div align=center>
                <table>
                    <tr>
                        <td style="padding: 2px; border-right: 1px solid; border-bottom: 1px solid;">{{ exp.conf_mat_rr }}</td>
                        <td style="padding: 2px; border-bottom: 1px solid;">{{ exp.conf_mat_br }}</td>
                        <td style="padding: 2px; border-width: 0 0 1px 1px; border-style: solid;">{{ exp.predicted_reals }}</td>
                    </tr>
                    <tr>
                        <td style="padding: 2px; border-width: 0 1px 1px 0; border-style: solid;">{{ exp.conf_mat_rb }}</td>
                        <td style="padding: 2px; border-bottom: 1px solid;">{{ exp.conf_mat_bb }}</td>
                        <td style="padding: 2px; border-width: 0 0 1px 1px; border-style: solid;">{{ exp.predicted_bogus }}</td>
                    </tr>
                    <tr>
                        <td style="padding: 2px; border-right: 1px solid;">{{ exp.total_reals }}</td>
                        <td style="padding: 2px; border-right: 1px solid;">{{ exp.total_bogus }}</td>
                        <td style="padding: 2px;">{{ exp.total_samples }}</td>
                    </tr>
                </table>
                </div>
                </div>
            </td>
            <td>
                <p><strong>Recall</strong>: {{ exp.recall|floatformat:2 }}</p>
                <p><strong>Precision</strong>: {{ exp.precision|floatformat:2 }}</p>
                <p><strong>F-measure</strong>: {{ exp.f_measure|floatformat:2 }}</p>
                <p><strong>FPR</strong>: {{ exp.false_positive_rate|floatformat:2 }}</p>
                <p><strong>Miss Rate</strong>: {{ exp.miss_rate|floatformat:2 }}</p>
            </td>
            {% if exp.platform == "3" %}
            <td>{{ exp.other_platform_name }} </td>
            {% else %}
            <td>{{ exp.get_platform_display }} </td>
            {% endif %}
            <td>{{ exp.description }}</td>
          </tr>
          {% endfor %}
        </tbody>
        </table>
    </div class="table-responsive">
    {% else %}
    <p>No experiments to show</p>
    {% endif %}
  </div class="panel-body">
</div class="panel panel-primary">

</div class="container-fluid">


<script>
  $(function() {
    $( ".datepicker" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "2000:2100",
      setDate: +0
    });
  });
  </script>

{% endblock %}

torosweb/rbmanager/templates/rbmanager/login_form.html
<!-- Modal -->
<div id="loginmodal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-sm">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Log in</h4>
      </div>

      <form method="post" role="form" action="{% url 'winnow:login' %}">
      <div class="modal-body">
      {% csrf_token %}
        <div class="form-group">
          <label class="sr-only" for="name">Username:</label>
          <input name="username" id="name" value="" class="form-control" type="text" placeholder="Username"/>
        </div>
        <div class="form-group">
          <label class="sr-only" for="password">Password:</label>
          <input name="password" id="password" value=""  class="form-control" type="password" placeholder="Password" />
        </div>
        <input type="hidden" name="next" value="{{ request.get_full_path }}" />
      </div class="modal-body">
      <div class="modal-footer">
        <button type="submit" class="btn btn-default">Log in</button>
      </div class="modal-footer">
      </form>

    </div class="modal-content">

  </div class="modal-dialog modal-sm">
</div id="loginmodal" class="modal fade" role="dialog">